### PR TITLE
Ensure onToggle is called when on is controlled but setOnState is called

### PR DESCRIPTION
**Pull request by bslinger**
**What**: Fix a bug introduced in #17 that prevents onToggle from being called when the internal setOnState is called.

**Why**: When `on` is controlled, onToggle should be called either when the controlled prop is change, or when the internal toggle actually occurs

**How**: I added a check in setOnState to compare the current `on` with the new state and call `onToggle` if necessary.

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
This looks good to me. Thanks!

**Comment by kentcdodds** [comment]
Looks like we need another test to get our code coverage goal. Could you please do that?

**Comment by bslinger** [comment]
Ah, just noticed that. Strange, shouldn't line 72 be covered since setOnState is being called in several tests? Sorry, I'm not as familiar with jest as I'd like to be!

**Comment by kentcdodds** [comment]
If you want to look at the coverage report, open `coverage/lcov-report/index.html` locally in your browser 👍 that could help.

**Comment by bslinger** [comment]
Ah thanks, I see, I had to make sure both branches of the `if` were covered - looks like this did the trick!

**Review by kentcdodds — APPROVED** [review]
Sweet! Thanks!

**Pull request merged**
